# default env if --set env=int|uat|prod not provided 
env: dev

name: "helmdemo"

# replicas
replicaCount:
   dev: 1
   int: 1
   uat: 2
   prod: 2

# Main container definiton
image:
  repository: docker.io/library
  name: nginx
  pullPolicy: IfNotPresent
  tag: "latest"
  
# Init Container definition
init_containers:
  enabled: false
  repository: docker.io/library
  image: busybox
  tag: "latest"
  pullPolicy: IfNotPresent
  command: ["/bin/ping"]
  args: ["$(SERVER)","-c","$(COUNT)"]
  env: |-
    - name: COUNT
      value: "10"
    - name: SERVER
      value: www.google.com

# mounting any already existing secret resources
# example - usage is common certs used across several apps and already created outside of this helm chart release
k8s_secrets:
  enabled: true
  resources:
  - name: truststore
    mountPath: /opt/application/certs/truststore.jks
    mountAs: file
  - name: artifactory-creds
    mountPath: /opt/application/artifactory.txt
    mountAs: env

# mainly:- credentils type of secret resources
# creating and mounting of new secrets from resources folder if they exist and are automatically mounted
# if enabled - then the certs/secrets must exist under resources/secrets/{int,uat,prod}
# secret created as <env>-<app-name>-secrets
secrets:
  enabled: true
  srcPath: "resources/secrets"
  mountPath: "/opt/application/secrets"
#  resources:
#  - name: dbesb-springboot-secret.properties
#    mountPath: /opt/application/secrets/dbesb-secrets.properties
#    mountAs: file
#  - name: certs-creds.properties
#    mountpath: ""
#    mountAs: env

# mainly:- certificates type of secret resources
# app specific certs if can be dropped into  resources/certs 
# secret created as <env>-<app-name>-certs
certs:
  enabled: true
  srcPath: "resources/certs"
  mountPath: "/opt/application/certs"
#  resources:
#  - name: app-certs.jks
#    mountPath: /opt/application/certs/app/app-certs.jks
#    mountAs: file

# app releated config files, env specific files under resources/config/{int,uat,prod}
# configmap created as <env>-<app-name>-config
config:
  enabled: true
  srcPath: "resources/config"
  mountPath: "/opt/application/config"
#  resources:
#   - name: dbidbk.properties
#     mountPath: /opt/application/config/dbidbk.properties
#     mountAs: file
#   - name: dbesb-java-args.properties
#     mountPath: /opt/applciation/config/dbesb-java-args.properties
#     mountAs: file
#   - name: java-args-env
#     mountPath: ""
#     mountAs: env
     
monitoring:
  enabled: false
  srcPath: "resources/monitoring"
  resources: 
  - path: resources/monitoring/config
    mountPath: /opt/applciation/monitoring/


serviceAccount:
  create: false
  name: default

securityContext: {}
#  capabilities: {}
#  readOnlyRootFilesystem: false
#  runAsNonRoot: true
#  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  dev:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  int:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  uat:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  prod:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 
    dev: 1
    int: 1
    uat: 1
    prod: 1
  maxReplicas:
    dev: 1
    int: 1
    uat: 2
    prod: 2
  targetCPUUtilizationPercentage:
    dev: 80
    int: 80
    uat: 75
    prod: 75
  targetMemoryUtilizationPercentage: 
    dev: 80
    int: 80
    uat: 75
    prod: 75

# usually meant for specialized  workloads/extreme customization
# may become complex using a single chart for such use-cases
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podSecurityContext: {}
imagePullSecrets: []
