{{- if .Values.config.enabled -}}
{{- $env := .Values.env -}}
{{- $basePath := .Values.config.srcPath -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include  "configmap.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- $root := . }}
  {{- range $name, $bytes := .Files.Glob "$basePath/*" }}
  {{ base $name }}: |-
{{ $root.Files.Get $name | indent 6 }}
  {{- end -}}
  {{- $root := . }}
  {{- range .Values.config.resources }}
  {{ .name }}: |-
  {{ $path := printf "%s/%s/%s" $basePath $env .name }}
{{ $root.Files.Get $path | indent 6 }}
  {{- end -}}
{{- end }}
