apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}-deploy
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ include "replicaCount" . }}
{{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.init_containers.enabled }}
      initContainers:
        - name: {{ include "app.name" .}}-init
          image: "{{ .Values.init_containers.repository }}/{{ .Values.init_containers.image }}:{{ .Values.init_containers.tag }}"
          imagePullPolicy: {{ .Values.init_containers.pullPolicy }}
          command: {{ .Values.init_containers.command }}
          {{- with .Values.init_containers.env }}
          env:
          {{- tpl . $ | nindent 12 }}
          {{- end -}}
      {{ end }}
      containers:
        - name: {{ include "app.name" .}}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          {{ include "env-vars"  . | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- include "resources" . }}
          volumeMounts:
            {{- include "volumeMounts" . | nindent 10 }}
      volumes:
        {{- include "volumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
