{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hct.name" . }}-hpa
  labels:
    {{- include "hct.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hct.name" . }}-deploy
  minReplicas: {{ include "minReplicas" .  }}
  maxReplicas: {{ include "maxReplicas" .  }}
  metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ include "targetCPUUtilizationPercentage" .  }}
  {{- end }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ include "targetMemoryUtilizationPercentage" . }}
  {{- end }}
{{- end }}
