{{- $env := .Values.env -}}
{{- $path := printf "%s/%s/*" .Values.certs.srcPath .Values.env -}}
{{- $certfiles := .Files.Glob $path -}}
{{- if and .Values.certs.enabled $certfiles -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.certs.name" .}}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $root := . }}
  {{- if .Values.certs.resources -}}
  {{- range .Values.certs.resources }}
  {{ .name }}: |-
  {{ $path := printf "%s/%s/%s" $.Values.certs.srcPath $env .name }}
  {{ $root.Files.Get $path  | indent 6 }}
  {{- end }}
  {{- else }}
  {{ ($certfiles).AsSecrets | nindent 4 }}
  {{- end -}}
{{- end -}}
