{{- $env := .Values.env -}}
{{- $path := printf "%s/%s/*" .Values.certs.srcPath .Values.env -}}
{{- $certfiles := .Files.Glob $path -}}
{{- if and .Values.certs.enabled $certfiles -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.certs.name" .}}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
{{- $root := . }}
{{- if .Values.certs.resources -}}
{{- range .Values.certs.resources }}
  {{ if eq .mountAs "file" }}
  {{ .name }}: |-
{{ $path := printf "%s/%s/%s" $.Values.certs.srcPath $env .name }}
{{ $root.Files.Get $path  |b64enc | indent 6 }}
  {{ end }}
{{- end }}
{{- else }}
{{ $path := printf "%s/%s/%s" $.Values.certs.srcPath $env .name }}
{{- range $name, $bytes := .Files.Glob $path }}
  {{ if eq .mountAs "file" }}
  {{ base $name }}: |-
{{ $root.Files.Get $name | b64enc |  indent 6 }}
  {{ end }}
{{- end }}
{{- end }}
{{- end }}
