{{- $env := .Values.env -}}
{{- $path := printf "%s/%s/*" .Values.secrets.srcPath .Values.env -}}
{{- $secretfiles := .Files.Glob $path -}}
{{- if and (.Values.secrets.enabled) ($secretfiles) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.creds.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $root := . }}
  {{- if .Values.secrets.resources -}}
  {{- range .Values.secrets.resources }}
  {{ .name }}: |-
  {{ $path := printf "%s/%s/%s" $.Values.secrets.srcPath $env .name }}
  {{ $root.Files.Get $path  | indent 6 }}
  {{- end }}
  {{- else }}
  {{- ($secretfiles).AsSecrets | nindent 4 }}
  {{ end }}
{{- end -}}
