{{- $env := .Values.env -}}
{{- $path := printf "%s/%s/*" .Values.secrets.srcPath .Values.env -}}
{{- $secretfiles := .Files.Glob $path -}}
{{- if and (.Values.secrets.enabled) .Values.secrets.resources -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.creds.name" . }}-env
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
{{- $root := . }}
{{- range .Values.secrets.resources }}
{{- if eq .mountAs "env" }}
{{ $path := printf "%s/%s/%s" $.Values.secrets.srcPath $env .name }}
{{ $root.Files.Get $path   | indent 6 }}
{{- end }}
{{- end }}
{{- end -}}

